/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Feedback struct {
	// Уникальный идентификатор отзыва
	Id string `json:"id"`

	Author *User `json:"author"`

	Receiver *User `json:"receiver"`

	Order *Order `json:"order"`
	// Комментарий к отзыву
	Description string `json:"description"`
	// Оценка заказа
	Points int32 `json:"points"`
}
