/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Пользователь системы
type User struct {
	// Уникальный идентификатор пользователя
	Id string `json:"id"`
	// Уникальный никнейм пользователя
	Username string `json:"username"`
	// Пароль пользователя
	Password string `json:"password"`
	// Имя пользователя
	Name string `json:"name"`
	// Фамилия пользователя
	Surname string `json:"surname"`

	UserState *UserState `json:"userState,omitempty"`

	UserType *UserType `json:"userType"`
}
