package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Car struct {
	// Уникальный идентификатор автомобиля
	ID uint32 `gorm:"primary_key;auto_increment"`

	OwnerID uint32
	Owner   User `gorm:"not null"`
	// Государственный регистрационный знак автомобиля
	LicensePlate string `gorm:"size:10;not null;unique"`

	PositionID uint32
	Position   Position

	SpecificationID uint32
	Specification   Specification `gorm:"not null"`
}
