package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Car struct {
	// Уникальный идентификатор автомобиля
	ID uint32 `json:"id" gorm:"primary_key;auto_increment"`

	Owner *User `json:"owner" gorm:"not null"`
	// Государственный регистрационный знак автомобиля
	LicensePlate string `json:"licensePlate" gorm:"size:10;not null;unique"`

	Position *Position `json:"position"`

	Specification *Specification `json:"specification" gorm:"not null"`
}
