/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

type Car struct {
	// Уникальный идентификатор автомобиля
	Id string `json:"id"`

	Owner *User `json:"owner"`
	// Государственный регистрационный знак автомобиля
	LicensePlate string `json:"licensePlate"`

	Position *Position `json:"position"`

	Specification *Specification `json:"specification"`
}
