package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Feedback struct {
	// Уникальный идентификатор отзыва
	ID       uint32 `json:"id" gorm:"primary_key;auto_increment"`
	AuthorID uint32 `json:"author_id"`
	Author   User   `json:"author" gorm:"ForeignKey:AuthorID;not null"`

	ReceiverID uint32 `json:"receiver_id"`
	Receiver   User   `json:"receiver" gorm:"ForeignKey:ReceiverID;not null"`

	OrderID uint32 `json:"order_id"`
	Order   Order  `json:"order" gorm:"ForeignKey:OrderID;not null"`
	// Комментарий к отзыву
	Description string `json:"description" gorm:"not null"`
	// Оценка заказа
	Points int32 `json:"points" gorm:"check:points >= 0;check:points <= 5;not null"`
}
