package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Feedback struct {
	// Уникальный идентификатор отзыва
	ID       uint32 `gorm:"primary_key;auto_increment"`
	AuthorID uint32
	Author   User `gorm:"not null"`

	ReceiverID uint32
	Receiver   User `gorm:"not null"`

	OrderID uint32
	Order   Order `gorm:"not null"`
	// Комментарий к отзыву
	Description string `gorm:"not null"`
	// Оценка заказа
	Points int32 `gorm:"check:points >= 0;check:points <= 5;not null"`
}
