package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Feedback struct {
	// Уникальный идентификатор отзыва
	ID uint32 `json:"id" gorm:"primary_key;auto_increment"`

	Author *User `json:"author" gorm:"not null"`

	Receiver *User `json:"receiver" gorm:"not null"`

	Order *Order `json:"order" gorm:"not null"`
	// Комментарий к отзыву
	Description string `json:"description" gorm:"not null"`
	// Оценка заказа
	Points int32 `json:"points" gorm:"check:points >= 0;check:points <= 5;not null"`
}
