package model

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Order struct {
	// Уникальный идентификатор автомобиля
	ID uint32 `json:"id" gorm:"primary_key;auto_increment"`

	Owner *User `json:"owner" gorm:"not null"`
	// Заголовок заказа
	Title string `json:"title" gorm:"not null"`
	// Описание заказа
	Description string `json:"description" gorm:"not null"`
	// Цена за исполнение заказа
	Price float64 `json:"price" gorm:"check:Price > 0;not null"`

	State *OrderState `json:"state" gorm:"not null"`

	From *Position `json:"from" gorm:"not null"`

	To *Position `json:"to" gorm:"not null"`

	Specification *Specification `json:"specification" gorm:"not null"`
}

func (u *Order) Scan(src interface{}) error {
	switch v := src.(type) {
	case string:
		return json.Unmarshal([]byte(v), u)
	case []byte:
		return json.Unmarshal(v, u)
	}
	return fmt.Errorf("cannot convert %T to My struct", src)
}

//nolint:hugeParam
func (u Order) Value() (driver.Value, error) {
	return json.Marshal(u)
}
