package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Order struct {
	// Уникальный идентификатор автомобиля
	Id string `json:"id"`

	Owner *User `json:"owner"`
	// Заголовок заказа
	Title string `json:"title"`
	// Описание заказа
	Description string `json:"description"`
	// Цена за исполнение заказа
	Price float64 `json:"price"`

	State *OrderState `json:"state"`

	From *Position `json:"from"`

	To *Position `json:"to"`

	Specification *Specification `json:"specification"`
}
