package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Order struct {
	// Уникальный идентификатор автомобиля
	ID uint32 `gorm:"primary_key;auto_increment"`

	OwnerID uint32
	Owner   User `gorm:"not null"`

	ExecutorIDRefer uint32 // TODO добавить в swagger

	ExecutorCarIDRefer uint32 // TODO добавить в swagger

	// Заголовок заказа
	Title string `gorm:"not null"`
	// Описание заказа
	Description string `gorm:"not null"`
	// Цена за исполнение заказа
	Price float64 `gorm:"check:Price > 0;not null"`

	State OrderState `gorm:"not null"`

	FromID uint32
	From   Position `gorm:"not null"`

	ToID uint32
	To   Position `gorm:"not null"`

	SpecificationID uint32
	Specification   Specification `gorm:"not null"`
}
