package model

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Position Координаты точки на карте
type Position struct {
	// Уникальный идентификатор записи координат
	ID uint32 `json:"id" gorm:"primary_key;auto_increment"`
	// Широта
	Latitude float64 `json:"latitude" gorm:"check:Latitude >= 0;check:Latitude <= 90;not null"`
	// Долгота
	Longitude float64 `json:"longitude" gorm:"check:Longitude >= -180;check:Longitude <= 180;not null"`
}

func (u *Position) Scan(src interface{}) error {
	switch v := src.(type) {
	case string:
		return json.Unmarshal([]byte(v), u)
	case []byte:
		return json.Unmarshal(v, u)
	}
	return fmt.Errorf("cannot convert %T to My struct", src)
}

//nolint:hugeParam
func (u Position) Value() (driver.Value, error) {
	return json.Marshal(u)
}
