package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// Position Координаты точки на карте
type Position struct {
	// Уникальный идентификатор записи координат
	ID uint32 `gorm:"primary_key;auto_increment"`
	// Широта
	Latitude float64 `gorm:"check:Latitude >= 0;check:Latitude <= 90;not null"`
	// Долгота
	Longitude float64 `gorm:"check:Longitude >= -180;check:Longitude <= 180;not null"`
}
