package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

type Specification struct {
	// Уникальный идентификатор автомобиля
	ID uint32 `gorm:"primary_key;auto_increment"`
	// Длина прицепа автомобиля
	Length float64 `gorm:"check:Length > 0;not null"`
	// Высота прицепа автомобиля
	Height float64 `gorm:"check:Height > 0;not null"`
	// Ширина прицепа автомобиля
	Width float64 `gorm:"check:Width > 0;not null"`
	// Цвет прицепа автомобиля
	Color string `gorm:"size:7;not null"`

	BodyType TrailerType `gorm:"not null"`

	LoadingPlaces LoadingPlaces `gorm:"not null"`
}
