/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// TrailerType : Тип прицепа грузовика
type TrailerType string

// List of TrailerType
const (
	DRY_VAN      TrailerType = "DryVan"
	FLATBED      TrailerType = "Flatbed"
	REFRIGERATED TrailerType = "Refrigerated"
	DROP_DECK    TrailerType = "DropDeck"
	STEP_DECK    TrailerType = "Step-Deck"
	DOUBLE_DROP  TrailerType = "DoubleDrop"
	LOWBOY       TrailerType = "Lowboy"
	HOT_SHOT     TrailerType = "HotShot"
	CONESTOGA    TrailerType = "Conestoga"
	CURTAINSIDE  TrailerType = "Curtainside"
)
