package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// UserState : Состояние пользователя
type UserState string

// List of UserState
const (
	ACTIVE    UserState = "ACTIVE"
	BANNED    UserState = "BANNED"
	SUSPENDED UserState = "SUSPENDED"
)
