/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package model

// UserType : Тип пользователя
type UserType string

// List of UserType
const (
	EXECUTOR UserType = "EXECUTOR"
	CUSTOMER UserType = "CUSTOMER"
	ADMIN    UserType = "ADMIN"
)
