package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// UserType : Тип пользователя
type UserType string

// List of UserType
const (
	STANDARD UserType = "STANDARD"
	ADMIN    UserType = "ADMIN"
)
