package model

/*
 * logistics-aggregator
 *
 * Aгрегатор логистических заказов
 *
 * API version: 1.0
 * Contact: f.kurbanov120303@yandex.ru
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

// User Пользователь системы
type User struct {
	// Уникальный идентификатор пользователя
	ID uint32 `gorm:"primary_key;auto_increment"`
	// Уникальный никнейм пользователя
	Username string `gorm:"size:100;not null;unique"`
	// Пароль пользователя
	Password string `gorm:"size:255;not null"`
	// Имя пользователя
	Name string `gorm:"size:255;not null"`
	// Фамилия пользователя
	Surname string `gorm:"size:255;not null"`

	UserState UserState `gorm:"not null"`

	UserType UserType `gorm:"not null"`
}
